language: python
python:
#  - '3.5'
  - '2.7'
#  - '3.4'
#  - '3.3'
#  - '3.2'
#  - '2.6'
#  - 'pypy'
#  - 'pypy3'
env:
  matrix:
    - ARGS=--is_master
    - ARGS=
sudo: false # Use container-based infrastructure
install: "pip install flake8"
script:
  - echo "Doing something... args=${ARGS}"
  - flake8 --ignore E303
  - echo "Done"
after_success:
  - ./travis_after_all.py ${ARGS}
  - cat .to_export_back
  - export $(cat .to_export_back)
  - if [ "$BUILD_LEADER" = "YES" ]; then
      if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeeded! PUBLISHING...";
        else
          echo "Some or all jobs failed";
       fi
    fi

after_failure:
  - python travis_after_all.py ${ARGS}
  - cat .to_export_back
  - export $(cat .to_export_back)
  - if [ "$BUILD_LEADER" = "YES" ]; then
       echo "Some or all jobs failed";
    fi
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
